# .github/workflows/rerun-failed-workflow.yml
name: Rerun Failed Workflow

on:
  issue_comment:
    types: [created]

jobs:
  rerun-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check if comment contains rerun command
        id: check_comment
        run: |
          echo "COMMENT_BODY=${{ github.event.comment.body }}" >> $GITHUB_ENV
          if [[ "${{ github.event.comment.body }}" == "/rerun" ]]; then
            echo "RERUN_COMMAND=true" >> $GITHUB_ENV
          fi
      - name: Get pull request owner
        if: env.RERUN_COMMAND == 'true'
        id: get_pr_owner
        run: |
          PR_NUMBER=$(echo ${{ github.event.issue.number }})
          PR_OWNER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | \
            jq -r '.user.login')
          echo "PR_OWNER=$PR_OWNER" >> $GITHUB_ENV
      - name: Check if comment author is pull request owner
        if: env.RERUN_COMMAND == 'true'
        id: check_author
        run: |
          COMMENT_AUTHOR=$(echo ${{ github.event.comment.user.login }})
          if [[ "$COMMENT_AUTHOR" == "$PR_OWNER" ]]; then
            echo "AUTHOR_IS_OWNER=true" >> $GITHUB_ENV
          fi
      - name: Rerun failed workflow
        if: env.RERUN_COMMAND == 'true' && env.AUTHOR_IS_OWNER == 'true'
        run: |
          # Get the workflow run ID of the last failed run
          WORKFLOW_RUN_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs" | \
            jq '.workflow_runs[] | select(.status == "completed" and .conclusion == "failure") | .id' | head -n 1)
          
          # Rerun the failed workflow
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$WORKFLOW_RUN_ID/rerun"